let number1;
let number2;
let number3;
let number4;
let number5;
number1=Math.floor(Math.random()*10+10);
number2=Math.floor(Math.random()*10+10);
number3=Math.floor(Math.random()*10+10);
number4=Math.floor(Math.random()*10+10);
number5=Math.floor(Math.random()*10+10);
let addition = number1+number2+number3+number4+number5;
console.log("Addition is :" +addition);
let average = addition/5;
console.log("Average is :" +average);